export const dummy = {
  timestamp: "string",
  transactionId: "string",
  statusCode: 0,
  status: "string",
  message: "string",
  msg: "string",
  success: true,
  data: {
    CAIS_Account: {
      CAIS_Account_DETAILS: [
        {
          AccountHoldertypeCode: 1,
          Account_Number: "XXXXXX0S04",
          Account_Status: 11,
          Account_Type: 1,
          Amount_Past_Due: "",
          CAIS_Account_History: [
            {
              Asset_Classification: "?",
              Days_Past_Due: "",
              Month: 5,
              Year: 2023,
            },
            {
              Asset_Classification: "?",
              Days_Past_Due: "",
              Month: 4,
              Year: 2023,
            },
          ],
          CAIS_Holder_Address_Details: [
            {
              Address_indicator_non_normalized: "",
              City_non_normalized: "",
              CountryCode_non_normalized: "IB",
              Fifth_Line_Of_Address_non_normalized: "",
              First_Line_Of_Address_non_normalized: "CHINAR4 CHS",
              Residence_code_non_normalized: "",
              Second_Line_Of_Address_non_normalized: "SV RAOD 4",
              State_non_normalized: 27,
              Third_Line_Of_Address_non_normalized: "",
              ZIP_Postal_Code_non_normalized: 400004,
            },
          ],
          CAIS_Holder_Details: [
            {
              Surname_Non_Normalized: "SHANAYA",
              First_Name_Non_Normalized: "JEH",
              Middle_Name_1_Non_Normalized: "",
              Middle_Name_2_Non_Normalized: "",
              Middle_Name_3_Non_Normalized: "",
              Alias: "",
              Gender_Code: 2,
              Income_TAX_PAN: "QAGPJ4289A",
              Date_of_birth: 19870811,
            },
          ],
          CAIS_Holder_ID_Details: [
            {
              Income_TAX_PAN: "QAGPJ4289A",
              EMailId: "",
            },
          ],
          CAIS_Holder_Phone_Details: [
            {
              EMailId: "",
              FaxNumber: "",
              Mobile_Telephone_Number: "",
              Telephone_Extension: "",
              Telephone_Number: 9295390874,
              Telephone_Type: "",
            },
          ],
          Consumer_comments: "",
          Credit_Limit_Amount: "",
          CurrencyCode: "INR",
          Current_Balance: 1000000,
          DateOfAddition: 20230410,
          Date_Closed: "",
          Date_of_First_Delinquency: "",
          Date_of_Last_Payment: "",
          Date_Reported: 20230510,
          DefaultStatusDate: "",
          Highest_Credit_or_Original_Loan_Amount: 2000000,
          Identification_Number: "OTHXXXXXXXX",
          Income: "",
          Income_Frequency_Indicator: "",
          Income_Indicator: "",
          LitigationStatusDate: "",
          Occupation_Code: "",
          Open_Date: 20220615,
          Original_Charge_Off_Amount: "",
          Payment_History_Profile: "????????????????????????????????????",
          Payment_Rating: "?",
          Portfolio_Type: "I",
          Promotional_Rate_Flag: "",
          Rate_of_Interest: "",
          Repayment_Tenure: 0,
          Scheduled_Monthly_Payment_Amount: "",
          Settlement_Amount: "",
          Special_Comment: "",
          Subscriber_comments: "",
          Subscriber_Name: "XXXXXXXXXX",
          SuitFiledWillfulDefaultWrittenOffStatus: "",
          SuitFiled_WillfulDefault: "",
          Terms_Duration: "",
          Terms_Frequency: "",
          Type_of_Collateral: "",
          Value_of_Collateral: "",
          Value_of_Credits_Last_Month: "",
          WriteOffStatusDate: "",
          Written_Off_Amt_Principal: "",
          Written_Off_Amt_Total: "",
          Written_off_Settled_Status: "",
        },
        {
          AccountHoldertypeCode: 1,
          Account_Number: "XXXXXX0S62",
          Account_Status: 93,
          Account_Type: 2,
          Amount_Past_Due: 4500000,
          CAIS_Account_History: [
            {
              Asset_Classification: "S",
              Days_Past_Due: 67,
              Month: 2,
              Year: 2023,
            },
          ],
          CAIS_Holder_Address_Details: [
            {
              Address_indicator_non_normalized: "",
              City_non_normalized: "",
              CountryCode_non_normalized: "IB",
              Fifth_Line_Of_Address_non_normalized: "",
              First_Line_Of_Address_non_normalized: "CHINAR4 CHS",
              Residence_code_non_normalized: "",
              Second_Line_Of_Address_non_normalized: "SV RAOD 4",
              State_non_normalized: 27,
              Third_Line_Of_Address_non_normalized: "",
              ZIP_Postal_Code_non_normalized: 400003,
            },
          ],
          CAIS_Holder_Details: [
            {
              Surname_Non_Normalized: "SHANAYA",
              First_Name_Non_Normalized: "JEH",
              Middle_Name_1_Non_Normalized: "",
              Middle_Name_2_Non_Normalized: "",
              Middle_Name_3_Non_Normalized: "",
              Alias: "",
              Gender_Code: 2,
              Income_TAX_PAN: "QAGPJ4289A",
              Date_of_birth: 19870811,
            },
          ],
          CAIS_Holder_ID_Details: [
            {
              Income_TAX_PAN: "QAGPJ4289A",
              EMailId: "",
            },
          ],
          CAIS_Holder_Phone_Details: [
            {
              EMailId: "",
              FaxNumber: "",
              Mobile_Telephone_Number: "",
              Telephone_Extension: "",
              Telephone_Number: 9295390874,
              Telephone_Type: "",
            },
          ],
          Consumer_comments: "",
          Credit_Limit_Amount: "",
          CurrencyCode: "INR",
          Current_Balance: 1000000,
          DateOfAddition: 20230210,
          Date_Closed: "",
          Date_of_First_Delinquency: "",
          Date_of_Last_Payment: "",
          Date_Reported: 20230210,
          DefaultStatusDate: "",
          Highest_Credit_or_Original_Loan_Amount: 1500000,
          Identification_Number: "OTHXXXXXXXX",
          Income: "",
          Income_Frequency_Indicator: "",
          Income_Indicator: "",
          LitigationStatusDate: "",
          Occupation_Code: "",
          Open_Date: 20220615,
          Original_Charge_Off_Amount: "",
          Payment_History_Profile: "N",
          Payment_Rating: 2,
          Portfolio_Type: "M",
          Promotional_Rate_Flag: "",
          Rate_of_Interest: "",
          Repayment_Tenure: 0,
          Scheduled_Monthly_Payment_Amount: "",
          Settlement_Amount: "",
          Special_Comment: "",
          Subscriber_comments: "",
          Subscriber_Name: "XXXXXXXXXX",
          SuitFiledWillfulDefaultWrittenOffStatus: "",
          SuitFiled_WillfulDefault: 1,
          Terms_Duration: "",
          Terms_Frequency: "",
          Type_of_Collateral: "",
          Value_of_Collateral: "",
          Value_of_Credits_Last_Month: "",
          WriteOffStatusDate: "",
          Written_Off_Amt_Principal: "",
          Written_Off_Amt_Total: "",
          Written_off_Settled_Status: "",
        },
        {
          AccountHoldertypeCode: 1,
          Account_Number: "XXXXXXXXDP02",
          Account_Status: 89,
          Account_Type: 5,
          Amount_Past_Due: 1000000,
          CAIS_Account_History: [
            {
              Asset_Classification: "?",
              Days_Past_Due: 120,
              Month: 5,
              Year: 2023,
            },
            {
              Asset_Classification: "?",
              Days_Past_Due: 120,
              Month: 4,
              Year: 2023,
            },
            {
              Asset_Classification: "?",
              Days_Past_Due: 120,
              Month: 2,
              Year: 2023,
            },
            {
              Asset_Classification: "?",
              Days_Past_Due: 120,
              Month: 1,
              Year: 2023,
            },
          ],
          CAIS_Holder_Address_Details: [
            {
              Address_indicator_non_normalized: "",
              City_non_normalized: "",
              CountryCode_non_normalized: "IB",
              Fifth_Line_Of_Address_non_normalized: "",
              First_Line_Of_Address_non_normalized: "CHINAR4 CHS",
              Residence_code_non_normalized: "",
              Second_Line_Of_Address_non_normalized: "SV RAOD 4",
              State_non_normalized: 27,
              Third_Line_Of_Address_non_normalized: "",
              ZIP_Postal_Code_non_normalized: 400003,
            },
          ],
          CAIS_Holder_Details: [
            {
              Surname_Non_Normalized: "SHANAYA",
              First_Name_Non_Normalized: "JEH",
              Middle_Name_1_Non_Normalized: "",
              Middle_Name_2_Non_Normalized: "",
              Middle_Name_3_Non_Normalized: "",
              Alias: "",
              Gender_Code: 2,
              Income_TAX_PAN: "QAGPJ4289A",
              Date_of_birth: 19870811,
            },
          ],
          CAIS_Holder_ID_Details: [
            {
              Income_TAX_PAN: "QAGPJ4289A",
              EMailId: "",
            },
          ],
          CAIS_Holder_Phone_Details: [
            {
              EMailId: "",
              FaxNumber: "",
              Mobile_Telephone_Number: "",
              Telephone_Extension: "",
              Telephone_Number: 9295390874,
              Telephone_Type: "",
            },
          ],
          Consumer_comments: "",
          Credit_Limit_Amount: "",
          CurrencyCode: "INR",
          Current_Balance: 4000000,
          DateOfAddition: 20230120,
          Date_Closed: "",
          Date_of_First_Delinquency: "",
          Date_of_Last_Payment: "",
          Date_Reported: 20230520,
          DefaultStatusDate: "",
          Highest_Credit_or_Original_Loan_Amount: 5600000,
          Identification_Number: "OTHXXXXXXXX",
          Income: "",
          Income_Frequency_Indicator: "",
          Income_Indicator: "",
          LitigationStatusDate: "",
          Occupation_Code: "",
          Open_Date: 20220615,
          Original_Charge_Off_Amount: "",
          Payment_History_Profile: "4?44????????????????????????????????",
          Payment_Rating: 4,
          Portfolio_Type: "I",
          Promotional_Rate_Flag: "",
          Rate_of_Interest: "",
          Repayment_Tenure: 0,
          Scheduled_Monthly_Payment_Amount: "",
          Settlement_Amount: "",
          Special_Comment: "",
          Subscriber_comments: "",
          Subscriber_Name: "XXXXXXXXXX",
          SuitFiledWillfulDefaultWrittenOffStatus: "",
          SuitFiled_WillfulDefault: 2,
          Terms_Duration: "",
          Terms_Frequency: "",
          Type_of_Collateral: "",
          Value_of_Collateral: "",
          Value_of_Credits_Last_Month: "",
          WriteOffStatusDate: "",
          Written_Off_Amt_Principal: "",
          Written_Off_Amt_Total: "",
          Written_off_Settled_Status: "",
        },
      ],
      CAIS_Summary: {
        Credit_Account: {
          CADSuitFiledCurrentBalance: 0,
          CreditAccountActive: 3,
          CreditAccountClosed: 0,
          CreditAccountDefault: 0,
          CreditAccountTotal: 3,
        },
        Total_Outstanding_Balance: {
          Outstanding_Balance_All: 6000000,
          Outstanding_Balance_Secured: 2000000,
          Outstanding_Balance_Secured_Percentage: 33,
          Outstanding_Balance_UnSecured: 4000000,
          Outstanding_Balance_UnSecured_Percentage: 67,
        },
      },
    },
    CAPS: {
      CAPS_Application_Details: [
        {
          Amount_Financed: 5000,
          Date_of_Request: 20240214,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1707909096676,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: "",
          Date_of_Request: 20240214,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1707899837575,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: "",
          Date_of_Request: 20240214,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1707895117545,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: "",
          Date_of_Request: 20240214,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1707893632499,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: "",
          Date_of_Request: 20240214,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1707893061777,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240213,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707823924794,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240213,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707817723260,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707739175318,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707738271430,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707738254090,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707738190970,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: "",
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707729519660,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 100000,
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1707721881178,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707721420006,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240212,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707702842515,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240210,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707550275576,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240210,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707550256820,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240210,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707550213416,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240210,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707550179191,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240210,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707550165289,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240210,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707550152097,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707473362666,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707473333231,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707473274373,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707473260140,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707472620137,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707468914317,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707468882192,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707468851803,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240209,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707468631432,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240208,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707392917529,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240208,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707392802891,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 1000,
          Date_of_Request: 20240208,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 7,
          Finance_Purpose: 99,
          ReportNumber: 1707392452346,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240120,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1705736992955,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240120,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1705692399966,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231229,
          Duration_Of_Agreement: 180,
          Enquiry_Reason: 14,
          Finance_Purpose: 48,
          ReportNumber: 1703832008363,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 300000,
          Date_of_Request: 20231221,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 1,
          Finance_Purpose: 99,
          ReportNumber: 1703151431746,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 105000,
          Date_of_Request: 20231211,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 16,
          Finance_Purpose: 55,
          ReportNumber: 1702294471161,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 70000,
          Date_of_Request: 20231211,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 16,
          Finance_Purpose: 55,
          ReportNumber: 1702273161695,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231205,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1701780182131,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231127,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1701064456831,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231127,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1701063389615,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231110,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699556681509,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231109,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699506257521,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231108,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1699421716179,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231107,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1699342537042,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231107,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1699339651538,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699008215975,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699006853094,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699006792415,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699006784824,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699006594331,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699006152118,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699006130038,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699005908811,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699005789493,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699005405690,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699004989501,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699004857663,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231103,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1699004635515,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 5000,
          Date_of_Request: 20231102,
          Duration_Of_Agreement: 6,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1698917727853,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 7000000,
          Date_of_Request: 20231031,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 3,
          Finance_Purpose: 99,
          ReportNumber: 1698735721323,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 7000000,
          Date_of_Request: 20231031,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 3,
          Finance_Purpose: 99,
          ReportNumber: 1698735687865,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20231027,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 7,
          Finance_Purpose: 23,
          ReportNumber: 1698411606124,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 10000,
          Date_of_Request: 20231027,
          Duration_Of_Agreement: 12,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1698409763677,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 2000000,
          Date_of_Request: 20230915,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 3,
          Finance_Purpose: 99,
          ReportNumber: 1694776424244,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 2000000,
          Date_of_Request: 20230915,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 3,
          Finance_Purpose: 99,
          ReportNumber: 1694776411674,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 2000000,
          Date_of_Request: 20230915,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 3,
          Finance_Purpose: 99,
          ReportNumber: 1694776344969,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 700000,
          Date_of_Request: 20230731,
          Duration_Of_Agreement: 30,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1690788780972,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 700000,
          Date_of_Request: 20230725,
          Duration_Of_Agreement: 30,
          Enquiry_Reason: 13,
          Finance_Purpose: 99,
          ReportNumber: 1690269381535,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 30000,
          Date_of_Request: 20230705,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 1,
          Finance_Purpose: 1,
          ReportNumber: 1688540002274,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 30000,
          Date_of_Request: 20230705,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 1,
          Finance_Purpose: 1,
          ReportNumber: 1688539973707,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 30000,
          Date_of_Request: 20230705,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 1,
          Finance_Purpose: 1,
          ReportNumber: 1688539856178,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 30000,
          Date_of_Request: 20230705,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 1,
          Finance_Purpose: 1,
          ReportNumber: 1688539843171,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 30000,
          Date_of_Request: 20230705,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 1,
          Finance_Purpose: 1,
          ReportNumber: 1688539746498,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 30000,
          Date_of_Request: 20230705,
          Duration_Of_Agreement: 1,
          Enquiry_Reason: 1,
          Finance_Purpose: 1,
          ReportNumber: 1688538525452,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
      ],
      CAPS_Summary: {
        CAPSLast180Days: 72,
        CAPSLast30Days: 33,
        CAPSLast7Days: 0,
        CAPSLast90Days: 43,
      },
    },
    CreditProfileHeader: {
      ReportDate: 20240306,
      ReportTime: 161142,
      Version: "V2.4",
      ReportNumber: 1709721702771,
    },
    Current_Application: {
      Current_Application_Details: {
        Amount_Financed: 0,
        Current_Applicant_Additional_AddressDetails: "",
        Current_Applicant_Address_Details: {
          BldgNoSocietyName: "",
          City: "Mumbai",
          Country_Code: "IB",
          FlatNoPlotNoHouseNo: "CHINAR4 CHS",
          Landmark: "",
          PINCode: 400004,
          RoadNoNameAreaLocality: "",
          State: 27,
        },
        Current_Applicant_Details: {
          Last_Name: "JEH",
          First_Name: "SHANAYA",
          Middle_Name1: "",
          Middle_Name2: "",
          Middle_Name3: "",
          Gender_Code: 2,
          IncomeTaxPan: "QAGPJ4289A",
          Date_Of_Birth_Applicant: 19870811,
          Telephone_Number_Applicant_1st: "",
          Telephone_Extension: "",
          Telephone_Type: "",
          MobilePhoneNumber: 9295390874,
          EMailId: "SHANAYA@example.com",
        },
        Current_Other_Details: {
          Employment_Status: " ",
          Income: 0,
          Marital_Status: "",
          Number_of_Major_Credit_Card_Held: "",
          Time_with_Employer: "",
        },
        Duration_Of_Agreement: 0,
        Enquiry_Reason: 99,
        Finance_Purpose: 99,
      },
    },
    Header: {
      MessageText: "",
      ReportDate: 20240306,
      ReportTime: 161142,
      SystemCode: 0,
    },
    Match_result: {
      Exact_match: "Y",
    },
    NonCreditCAPS: {
      CAPS_Application_Details: [
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721702077,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721682153,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721682876,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721680456,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721679721,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721671081,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721670397,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721668645,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721667955,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721647241,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721646588,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721580217,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721579596,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721406796,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721406111,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721350259,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721349565,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721318523,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721317789,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721260282,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721260939,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721098408,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240306,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709721097760,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709646074065,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709646073379,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709646044258,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709646043453,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709645394072,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709645394720,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709645145035,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709645145945,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709644217088,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709644216442,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709644207112,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709644206170,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709639767550,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709639766849,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709638055338,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709638054199,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709626957493,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709626956279,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709621176571,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709621175893,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709619165199,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709619165884,
          ReportTime: 161142,
          Subscriber_code: "OTHXXXXXXXX",
          Subscriber_Name: "XXXXXXXXXX",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709618230490,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709618226051,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709618144225,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709618143481,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617717064,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617716377,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617616277,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617616995,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617604021,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617603330,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617590402,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709617589693,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615716123,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615716874,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615705129,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615704378,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615696232,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615696944,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615480345,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615479284,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615445803,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709615444720,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614773256,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614772603,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614622660,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614621975,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614614691,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614613984,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614604047,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614602678,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614522090,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614521433,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614007407,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709614006743,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613859170,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613858530,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613842386,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613841020,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613637355,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613636168,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613368347,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613367669,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613334288,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613334941,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613271624,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613270965,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613086289,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613086968,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613038099,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613038735,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613019941,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709613018633,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709612913294,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709612912539,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
        {
          Amount_Financed: 0,
          Date_of_Request: 20240305,
          Duration_Of_Agreement: 0,
          Enquiry_Reason: 99,
          Finance_Purpose: 99,
          ReportNumber: 1709612875042,
          ReportTime: 161142,
          Subscriber_code: 1552,
          Subscriber_Name: "LTCV CREDIT PVT LTD",
        },
      ],
      NonCreditCAPS_Summary: {
        NonCreditCAPSLast180Days: 100,
        NonCreditCAPSLast30Days: 100,
        NonCreditCAPSLast7Days: 100,
        NonCreditCAPSLast90Days: 100,
      },
    },
    SCORE: {
      FCIREXScore: 611,
      FCIREXScoreConfidLevel: "",
    },
    TotalCAPS_Summary: {
      TotalCAPSLast180Days: 172,
      TotalCAPSLast30Days: 133,
      TotalCAPSLast7Days: 100,
      TotalCAPSLast90Days: 143,
    },
    UserMessage: {
      UserMessageText: "Normal Response",
    },
    message: "No Record Found",
  },
  packageVersion: "string",
  responseCode: 0,
};
