name: Frontend Deploy on self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build Frontend
        run: |
          cd /home/githubrunner/proplex-admin-v2-main

          npm install
          npm run build

          sudo rm -rf /var/www/proplex-admin/*
          sudo cp -r dist/* /var/www/proplex-admin/

      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx --no-block
